define([],function () {

        var Constants = {
            defaultLocale: "en",
            defaultCard: "challenge",
            markupLocation: "js/app/templates/",
            contentLocation: "js/app/locale/",
            saveToStorageOnChange: true,
            useSessionStorage: true,
            heartBeatAPIPath: "",
            validateEZAppPath: "",
            submitEZAppPath: "",
            stateErrorMessage: "Error: Please select a state",
            zipCodeErrorMessage: "Error: Please enter a zipcode",
            radioErrorMessage: "Error: Please select an option",
            dropDownErrorMessage: "Error: Please select an option from the dropdown",
            emailErrorMessage: "Error: Please enter an email address",
            emailInvalidErrorMessage: "Error: Please enter a valid email address",
            raceErrorMessage: "Error: Please enter a race",
            raceSpecCharErrorMessage: "Error: Please remove special characters or numbers",
            specCharErrorMessage: "Error: Please remove special characters",
            currencyErrorMessage: "Error: Please enter amount",
            currencyInvalidErrorMessage: "Error: Please enter valid currency",
            selectErrorMessage: "Error: Please select a person",
            enterNameErrorMessage: "Error: Please enter a name",
            checkBoxErrorMessage: "Error: Please select at least one checkbox",
            policyNumErrorMessage: "Error: Please enter a policy number",
            zipCodeInvalidErrorMessage: "Error: Please enter a valid zipcode",
            streetErrorMessage: "Error: Please enter a street name",
            cityErrorMessage: "Error: Please enter a city",
            countyErrorMessage: "Error: Please enter a county",
            ssnInvalidErrorMessage: "Error: Please enter a valid ssn",
            dobInvalidErrorMessage: "Error: Please enter a valid dob",
            EmpNameErrorMessage: "Error: Please enter employer name",
            EmpStreetErrorMessage: "Error: Please enter employer street address",
            EmpCityErrorMessage: "Error: Please enter employer city",
            EmpZipErrorMessage: "Error: Please enter employer zipcode",
            EmpCountyErrorMessage: "Error: Please enter employer county",
            EmpPhNumErrorMessage: "Error: Please enter employer phone number",
            EmpEarnErrorMessage: "Error: Please enter amount earned",
            EmpHoursErrorMessage: "Error: Please enter hours worked",
            policyNumErrorMessage: "Error: Please enter a policy number",
            AuthTokenErrorMessage: "Error getting auth token response header",
            LocationResponseErrorMessage: "Error getting location response header",
            ScreeningIdErrorMessage: "Error getting Screening Id response header",
            SBMStates: ['CA','CO','CT','DC','HI','ID','KY','MD','MA','MN','NV','NM','NY','OR','RI','VT','WA'],
            AuthResponseHeader: "X-Auth-Token",
            AuthHiddenInput: "#authtoken",
            LocationResponseHeader: "location",
            ScreeningIdHeader: "screening_id",
            ScreeningHiddenInput: "#screeningid"

        };

        return Constants;
});
